In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

#create a synthetic dataset for demonstration

In [8]:
x,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=1)
x

array([[-2.10118662, -0.24720775, -1.98933489, ...,  2.07052553,
         0.09152688, -2.37639956],
       [ 0.32370343, -0.12689445, -1.30952433, ...,  1.18481987,
        -0.186802  ,  1.96932634],
       [ 2.23203753,  0.33412256, -0.85270339, ..., -0.06644818,
        -0.31388129,  1.49917393],
       ...,
       [-1.16966316,  0.2306405 , -2.71039374, ...,  0.02149968,
        -1.06680089,  0.52886752],
       [-2.64618249, -0.11784427,  0.14937733, ...,  0.34047267,
        -0.27694042, -0.87101392],
       [-4.07569534, -0.33130612, -0.11181622, ..., -0.4164757 ,
         0.36444447, -0.534328  ]])

In [11]:
pd.DataFrame(x)


0         1         2         3         4         5         6  \
0   -2.101187 -0.247208 -1.989335 -1.484556  1.128668 -0.925564  1.210290   
1    0.323703 -0.126894 -1.309524 -0.022738 -0.398725  0.280419  0.034598   
2    2.232038  0.334123 -0.852703  3.289016  0.331944  0.044767 -2.233844   
3   -0.428456  1.627132  0.484649  0.938373  1.339947 -0.869036  0.943132   
4    0.386012  0.338141 -0.186530  2.369137  1.667284 -0.979107  0.951526   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.148812 -0.048464  0.555170 -2.167311 -0.595136  0.237045 -1.241394   
996  1.585814  1.269868  1.193456  2.321360  0.222056  0.040255  2.260748   
997 -1.169663  0.230641 -2.710394 -3.217224 -1.509607  0.795293 -0.854581   
998 -2.646182 -0.117844  0.149377 -0.377960  2.755272 -1.983281 -1.865016   
999 -4.075695 -0.331306 -0.111816 -2.867222  2.200368 -1.802118 -1.288487   

            7         8         9  
0    2.070526  0.091527 -2.376400  
1    1.184820 -0.186802  1.969326  
2   -0.066448 -0.313881  1.499174  
3    0.713558 -0.468041  0.075341  
4    0.398790  0.729005  0.372213  
..        ...       ...       ...  
995 -0.144619 -0.136638 -1.363868  
996 -0.182916 -0.959332  0.263967  
997  0.021500 -1.066801  0.528868  
998  0.340473 -0.276940 -0.871014  
999 -0.416476  0.364444 -0.534328  

[1000 rows x 10 columns]

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)


In [13]:
x_train

array([[ 1.48829065, -2.10561639,  0.44173351, ..., -1.03111252,
         0.35026682,  0.1847476 ],
       [-1.75714143, -0.81391586, -0.78245291, ..., -1.14168096,
        -1.01500282,  1.07154926],
       [-0.63586326, -1.21522542, -1.06027382, ..., -0.76815848,
         0.26068848,  0.50031952],
       ...,
       [-0.79905141,  0.23223348, -1.37175136, ..., -1.44026512,
         0.03447448, -0.33548058],
       [-0.70308218,  0.2756734 ,  0.78799635, ...,  0.53188154,
         0.11443758, -0.82692529],
       [ 0.88650532, -0.63260211,  2.00213202, ...,  1.85691531,
         0.13705826, -0.44617634]])

In [14]:
x_train.shape

(700, 10)

In [15]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,

In [16]:
y_train.shape

(700,)

In [17]:
x_test

array([[-6.08812659e-01,  9.45886375e-01,  1.08281307e+00, ...,
         2.35989981e-01, -3.73476455e-01, -1.32110657e+00],
       [ 3.51627962e-01, -1.82921963e+00,  2.90828716e-03, ...,
        -1.20710467e-01, -8.84105546e-01, -1.30189483e+00],
       [-3.71005924e-01, -2.57533128e-01, -5.92706880e-01, ...,
        -4.70424480e-01, -4.99354803e-01, -1.98663988e-01],
       ...,
       [ 7.78360797e-01, -6.40502456e-01, -1.75340691e+00, ...,
        -1.86252444e-01, -1.47886969e-01,  7.51920881e-01],
       [ 1.43912403e+00, -4.67458752e-01, -3.34818067e-02, ...,
        -4.69674994e-01,  1.06215723e-01, -8.03833864e-01],
       [-2.62889557e+00, -2.21611612e-02,  8.41409399e-01, ...,
         9.89527992e-01, -2.92530504e+00,  5.85104557e-01]])

In [18]:
x_test.shape

(300, 10)

In [19]:
y_test.shape

(300,)